Fix issue in calendar date picker
RUGSoftEng/2018-Tuberculosis-iOS pull request #41
Opened 2018-04-16 20:56 UTC by NDrong

This fixes an issue in the calendar date picker where a newly selected
date would not trigger a rebuild in the medicine tab, due to a missing
call to setState.

2018-04-16 21:03 UTC, NDrong commented
It appears I was a little too eager to fix this one... The previous commit does not resolve the issue. 
I'll look further into this tomorrow.

2018-04-16 21:11 UTC, NDrong commented
Never mind, the previous commit **does** fix the issue. Turns out that I was running a cached build on my device, making it seem as if the issue wasn't resolved...

2018-04-17 09:02 UTC, juliusvdijk requested changes
Beter maak je een functie setDate die `_selectedDate = today` doet en daarna die onDateSelected called. En dan overal waar het nu handmatig gaat, dan call je die functie.

2018-04-17 09:12 UTC, NDrong commented
Implemented.

2018-04-17 09:14 UTC, juliusvdijk approved these changes

2018-04-17 09:14 UTC, merged