Retrieve topics and videos with web requests to API
RUGSoftEng/2018-Tuberculosis-iOS pull request #44
Opened 2018-04-17 11:49 UTC by hiddefolkertsma

2018-04-17 12:36 UTC, ndrong requested changes
Throws an exception at runtime:
```The following assertion was thrown building InformationTabPage(dirty):
type 'Future<List<dynamic>>' is not a subtype of type 'Future<List<String>>' where
Future is from dart:async
List is from dart:core

2018-05-14 14:21 UTC, juliusvdijk commented
Ik heb het gefixt.

2018-05-15 12:53 UTC, ndrong approved these changes

2018-05-15 12:53 UTC, NDrong commented
Love it.

2018-05-15 12:54 UTC, merged